base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from .forms import LoginForm

urlpatterns = [
    path('', views.Home.as_view(template_name='base/inicio.html'), name='inicio'),

    #Auntenticacion
    path('login/', auth_view.LoginView.as_view(template_name='base/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_view.LogoutView.as_view(next_page = 'base:login'), name='logout'),
    path('informedisc/<slug:val>', views.ResultadoDisc.as_view(template_name='base/informedisc.html'), name='informe_disc'),
    path('informediscCare/<slug:val>', views.ViewGraficoCare.as_view(template_name='base/informediscCare.html'), name='grafico_care'),
    path('informediscword/<slug:val>', views.DescargarWord.as_view(), name='informe_dcl'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

disc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('base.urls','base'), namespace='base')),
]

base/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, SetPasswordForm, PasswordResetForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus':'True', 'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control'}))

base/views.py
from typing import Any
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin,\
     PermissionRequiredMixin
from django.views import generic
from . import GetDataframe
import imgkit
from docxtpl import DocxTemplate, InlineImage
from docx.shared import Mm
from django.conf import settings
import os
import tempfile
import datetime
import zoneinfo

zona_asuncion = zoneinfo.ZoneInfo("America/Asuncion")

# Create your views here.
class Home(LoginRequiredMixin, generic.TemplateView):
    login_url='base:login'
    def get(self, request):
        total = GetDataframe.df_info_inicial()
        columns = total.columns.values
        dict_total = total.to_dict('records')
        return render(request, 'base/disctotal.html', locals())

    
class ResultadoDisc(LoginRequiredMixin, generic.TemplateView):
    def get(self, request, val):
        val_int = int(val)
        val_int -= 1
        total = GetDataframe.carga_total_completo(val_int)
        total_ = total.iloc[:,10:14].T
        disc_list_pc = total_[0].values.tolist()
        care_list = GetDataframe.list_care_for_graf(val_int)
        total.columns = total.columns.str.replace(" ", "_")
        dict_total = total.to_dict('records')
        #valor_url = request.build_absolute_uri(reverse('base:grafico_care', args=[val_int]))
        graf_disc = GetDataframe.get_disc_graf(val_int)
        graf_care = GetDataframe.get_grafico_polar_care_render(val_int)
        graf_lider = GetDataframe.get_grafico_polar_liderazgo_render(val_int)
        """ con = imgkit.config(wkhtmltoimage='C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe')
        imgkit.from_url(valor_url , 'out.png', config=con) """
        return render(request, 'base/informedisc.html', locals())


class ViewGraficoCare(generic.TemplateView):
    def get(self, request, val):
        val_int = int(val)
        total = GetDataframe.carga_total_completo(val_int)
        total.columns = total.columns.str.replace(" ", "_")
        care_list = GetDataframe.list_care_for_graf(val_int)
        dict_total = total.to_dict('records')
        return render(request, 'base/informediscCare.html', locals())
    

class DescargarWord(generic.TemplateView):
    def get(self, request, val):
        val_int = int(val)
        hora_asuncion = datetime.datetime.now(zona_asuncion)
        hora_asuncion = hora_asuncion.strftime('%d/%m/%Y')
        info_test = GetDataframe.info_test_total(val_int)
        name = info_test['Nombre y apellido'].values.tolist()
        #Dict info total DCL
        total = GetDataframe.carga_total_completo(val_int)
        total.columns = total.columns.str.replace(" ", "_")
        dict_total = total.to_dict('records')
        dict_total_fin = dict_total[0]
        response = HttpResponse(content_type='application/msword')
        response['Content-Disposition'] = f'attachment; filename="{name[0]}.docx"'
        
        path_plantilla = os.path.join(settings.BASE_DIR,'base', 'plantilla', 'Plantilla_Informe.docx') 
        doc = DocxTemplate(path_plantilla)
        graf_care = GetDataframe.get_grafico_polar_care_word(val_int)
        graf_lider = GetDataframe.get_grafico_polar_liderazgo_word(val_int)
        graf_disc = GetDataframe.get_disc_word(val_int)
        fp = tempfile.NamedTemporaryFile()
        with open(f"{fp.name}.png", 'wb') as temp_file:
            temp_file.write(graf_care)
            img_temp = str(temp_file.name)
            imagen = InlineImage(doc, img_temp, width=Mm(90), height=Mm(85))
        fp2 = tempfile.NamedTemporaryFile()
        with open(f"{fp2.name}.png", 'wb') as temp_file2:
            temp_file2.write(graf_lider)
            img_temp = str(temp_file2.name)
            imagen2 = InlineImage(doc, img_temp, width=Mm(90) )
        fp3 = tempfile.NamedTemporaryFile()
        with open(f"{fp3.name}.png", 'wb') as temp_file3:
            temp_file3.write(graf_disc)
            img_temp = str(temp_file3.name)
            imagen3 = InlineImage(doc, img_temp, width=Mm(60))
        nombre = f"{request.user.first_name} {request.user.last_name}"
        context = {'imagen': imagen, 'dict_total_fin': dict_total_fin, 'imagen2': imagen2, 'imagen3': imagen3, 'hora': hora_asuncion, 'user': nombre}
        doc.render(context)
        doc.save(response)
        return response

base/templates/base/disctotal.html
{% extends 'base/base.html' %}
{% block title %}Resultados DISC{% endblock %}
{% block body %} 

<div class="container">
    <h1 class="text-center display-1">Test DCL</h1>
    <table
          id="table"
          data-pagination="true"
          data-search="true"
          data-toggle="table"
          data-show-columns="true"
          data-locale="es-PY"
          data-show-columns-toggle-all="true"
    >
        <thead>
            <th>Acciones</th>
            {% for col in columns %}
            <th data-sortable="true">{{col}}</th>

            {% endfor %}

        </thead>
        
        <tbody>
            {% for key in dict_total %}
            <tr>
                {% for row, val in key.items %}
                    {% if row == "Id" %}
                    <td>
                        <a href="{% url "base:informe_disc" val %}" class="btn btn-warning btn-circle" role="button" ><i class="far fa-edit">Informe</i></a>
                    </td>
                    {% endif %}
                <td>{{val}}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
        
    </table>
</div>

{% endblock %}

base/templates/base/informediscCare.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Grafico Disc {% endblock %}

{% block css_page %}
    {% comment %} <script src="{% static 'base/highcharts-8.1.2/highcharts.js' %}"></script>
    <script src="{% static 'base/highcharts-8.1.2/modules/exporting.js' %}"></script>
    <script src="{% static 'base/highcharts-8.1.2/modules/export-data.js' %}"></script>
    <script src="{% static 'base/highcharts-8.1.2/modules/accessibility.js' %}"></script> {% endcomment %}

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-more.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>

    <style type='text/css'>
        body{
            font-family: 'Roboto', sans-serif;
        }
        .nuevo-estilo {
            margin: 15px 0px;
            background-color: #EFEDF1;
            border: 1px solid #E2E3E8;
            padding: 10px 1px;
        }
        .estilotabla {
            border-color: black;
            border-width: 2px;
            border-style: solid;
            font-weight: bold;
        }
        .estilotabla2 {
            border-color: black;
            border-width: 1px;
            border-style: solid;
        }
    </style>
{% endblock %}
{% block navigation %}{% endblock %}
{% block header %}{% endblock %}
{% block body %}
<div class="container">
    <h3 class="text-center">Datos Personales</h3>
    <div class="row">
        <div class="col-lg-12">
            <div id="container2"></div>
        </div>
    </div>
</div>
{% endblock %}
{% block js_page %} 
{% for info in dict_total %}
<script type="application/javascript">    
    Highcharts.chart('container2', {

        chart: {
            polar: true,
            type: 'line'
        },
    
        accessibility: {
            description: 'Resultados test CARE en un gráfico de tipo telaraña'
        },
    
        title: {
            text: 'Trabajo en Equipo'
        },
    
        pane: {
            size: '80%'
        },
    
        xAxis: {
            categories: [
                'Espontaneo', 'Normativo', 'Metódico', 'Conceptual'
            ],
            tickmarkPlacement: 'on',
            lineWidth: 0
        },
    
        yAxis: {
            gridLineInterpolation: 'polygon',
            lineWidth: 0,
            min: 0
        },
    
        tooltip: {
            shared: true,
            pointFormat: '<span style="color:{series.color}">{series.name}: <b>' +
                '{point.y:,.0f}</b><br/>'
        },
    
        legend: {
            enable: false
        },
    
        series: [{
            name: 'Puntaje',
            data: {{care_list|safe}},
            pointPlacement: 'on'
        }],
    
        responsive: {
            rules: [{
                condition: {
                    maxWidth: 500
                },
                chartOptions: {
                    legend: {
                        align: 'center',
                        verticalAlign: 'bottom',
                        layout: 'horizontal'
                    },
                    pane: {
                        size: '70%'
                    }
                }
            }]
        }
    
    });
   
</script>
{% endfor %}
{% endblock %}

base/templates/base/inicio.html
{% extends 'base/base.html' %}

base/templates/base/login.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Inicio sesion{% endblock %}
{% block navigation %}{% endblock %}
{% block header %}{% endblock %}
{% block content %}{% endblock %}

{% block login %}
<!-- [ auth-signin ] start -->
<div class="auth-wrapper">
	<div class="auth-content container">
		<div class="card">
			<div class="row align-items-center">
				<div class="col-md-6">
					<div class="card-body">
						<img src="{% static 'base/images/logo-dark.png' %}" alt="" class="img-fluid mb-4">
						<h4 class="mb-3 f-w-400">Iniciar sesión</h4>
						<form action="" method="post" novalidate>
                            {% csrf_token %}
                            {% for fm in form %}
                                {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
                                <br>
                            {% endfor %}
                            <input type="checkbox" id="box" onclick ="reveal()">  
                            <small>Mostrar contraseña</small>
                            <br>
                            <!-- <small><a href="" class="text-danger">Olvidó contraseña?</a></small> <br> -->
                            <input type="submit" value="Login" class="btn btn-primary mt-4"> <br>
                            
                            <!-- <div class="tex-center text-primary fw-bold">
                                <small>No tiene cuenta? <a href="" class="text-danger">Registrese</a></small>
                            </div> -->
                            {% if form.non_field_errors %}
                            {% for error in form.non_field_errors  %}
                                <p class="alert alert-danger my-3">{{error}}</p>
                            {% endfor %}
                            {% endif %}
        
                            {% if messages %}
                            {% for msg in messages %}
                                <div class="alert alert-{{msg.tags}}" role="alert">
                                    {{msg}}
                                </div>
                            {% endfor %}
                            {% endif %}
						</form>
					</div>
				</div>
				<div class="col-md-6 d-none d-md-block">
					<img src="../static/images/auth-bg.jpg" alt="" class="img-fluid">
				</div>
			</div>
		</div>
	</div>
</div>
<!-- [ auth-signin ] end -->
{% endblock %}
{% block js_page %} 
<script type="text/javascript">
    function reveal()
    {
    if(document.getElementById('box').checked)
       {document.getElementById("id_password").type='text';}
    else
    document.getElementById("id_password").type='password';
    }
</script> 
{% endblock %}
<!-- Required Js -->
<!--<script src="../assets/js/vendor-all.min.js"></script>
<script src="../assets/plugins/bootstrap/js/bootstrap.min.js"></script>


<div class="footer-fab">
    <div class="b-bg">
        <i class="fas fa-question"></i>
    </div>
    <div class="fab-hover">
        <ul class="list-unstyled">
            <li><a href="../doc/index-bc-package.html" target="_blank" data-text="UI Kit" class="btn btn-icon btn-rounded btn-info m-0"><i class="feather icon-layers"></i></a></li>
            <li><a href="../doc/index.html" target="_blank" data-text="Document" class="btn btn-icon btn-rounded btn-primary m-0"><i class="feather icon feather icon-book"></i></a></li>
        </ul>
    </div>
</div>


</body>

</html>-->